services:

  server:
    image: subpub_server
    container_name: subpub_server
    build:
      dockerfile: ./server/server.Dockerfile
      context: .
    environment:
      - SERVER_IS_DEBUG=${SERVER_IS_DEBUG-false}
      - SERVER_LISTENER_PORT=${SERVER_LISTENER_PORT-8090}
      - SERVER_LISTENER_HOST=${SERVER_LISTENER_HOST-0.0.0.0}
    expose:
      - "${SERVER_LISTENER_PORT-8090}:${SERVER_LISTENER_PORT-8090}"
    ports:
      - "${SERVER_LISTENER_PORT-8090}:${SERVER_LISTENER_PORT-8090}"
  
  client1:
    image: client1
    container_name: client1
    build:
      dockerfile: ./client1/client1.Dockerfile
      context: .
    environment:
      - CLIENT1_IS_DEBUG=${CLIENT1_IS_DEBUG-false}
      - CLIENT1_LISTENER_PORT=${CLIENT1_LISTENER_PORT-8089}
      - CLIENT1_LISTENER_HOST=${CLIENT1_LISTENER_HOST-0.0.0.0}
      - SERVER_LISTENER_PORT=${SERVER_LISTENER_PORT-8090}
      - SERVER_LISTENER_HOST=${SERVER_LISTENER_HOST-0.0.0.0}

    expose:
      - "${CLIENT1_LISTENER_PORT-8089}:${CLIENT1_LISTENER_PORT-8089}"
    ports:
      - "${CLIENT1_LISTENER_PORT-8089}:${CLIENT1_LISTENER_PORT-8089}"
    depends_on:
      server:
        condition: service_started
